[package]
name = "backend-migrator"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
tokio = { workspace = true }
sea-orm-migration = { version = "1.1.2", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
] }
