[package]
name = "backend-entity"
version = "0.1.0"
edition = "2021"

[dependencies]
schemars = { version = "0.8.21", features = [
    "uuid1",
    "rust_decimal",
    "chrono",
] }
sea-orm = { workspace = true }
